spring:
  application:
    name: web-core-service
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    url: ${LSD_WEB_DB_SOURCE:jdbc:mysql://localhost:3306/spring_boot_lsd}
    username: ${LSD_WEB_DB_USER:root}
    password: ${LSD_WEB_DB_PASSWORD:1234$}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${LSD_WEB_MAX_POOL_SIZE:15}
  jpa:
    show-sql: ${LSD_WEB_SHOW_SQL:true}
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.jdbc.batch_size: 2000
      hibernate.id.new_generator_mapping: true
      hibernate.dialect: org.hibernate.dialect.MySQL57InnoDBDialect
      hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      hibernate.format_sql: true
      hibernate.show_sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8300
  error:
    include-stacktrace: never
lsd:
  async:
    corePoolSize: ${LSD_WEB_CORE_POOL_SIZE:5}
    maxPoolSize: ${LSD_WEB_MAX_POOL_SIZE:15}
    queueCapacity: ${LSD_WEB_QUEUE_CAPACITY:5000}
jwt:
  secret: ${AUTH_SECRET_KEY:LSDSecretKey}
  expires: ${TOKEN_EXPIRES:1800000}
file:
  folder-upload: ${LSD_WEB_FOLDER_UPLOAD:var/www/uploads}